### ISSUE TITLE
前端面试题

### ISSUE THREAD

**Issue by MaelWeb** [yh-yunchuang-fe/funy-front-end#1]
### 2. Javascript  new操作符都做了哪些事情。 比如执行下述代码时发生了哪些事情？
```js
 function person(name, age) {
       this.name = name;
       this.age = age;
   }

  var Bill = new person('Bill', 20);
```

### 5. 下面的代码打印出来的是？
```js
function addTen(num) {
    num += 10;
    return num;
}
var count = 20;
var result = addTen(count);

console.log(count); // ?
console.log(result); // ?



function setName(obj) {
    obj.name = "Nicholas";
    // obj = new Object();
    // obj.name = "Greg";
}

var person = new Object();
setName(person);
console.log(person.name); // ?
```

### 11. 正则表达式。 写一个函数，调换数字和字符串的顺序:

``` js
/**
 * abc123     =>    123abc
 * China2017  =>   2017China
 **/


```

### 12. Event Loop 是否了解? 下面这段代码输出顺序？

```js
Promise.resolve().then(function promise1 () {
    console.log('promise1');
})

setTimeout(function setTimeout1 (){
    console.log('setTimeout1')
    Promise.resolve().then(function  promise2 () {
       console.log('promise2');
    })
}, 0)

setTimeout(function setTimeout2 (){
   console.log('setTimeout2')
}, 0)
```

### 13. 怎样优化下面这段代码？

```js

function getData(filter) {
    get(`/getSomeData1?filter1=${filter}`, data1 => {

        get(`/getSomeData2?filter2=${data1}`, data2 => {

            get(`/getSomeData2?filter3=${data2}`, data => {
                console.log(data);
            });
        });
    });
}

getData('test')

```

###  14. foo的值是什么？
```js
var foo = 10 + '20';
```

### 15. window.foo的值是什么？
```js
( window.foo || ( window.foo = "bar" ) );
```

### 16. 如何实现以下函数？
```js
add(2, 5); // 7
add(2)(5); // 7
```

### 17. foo.x的值是什么？
```js
var foo = { n: 1 };
var bar = foo;
foo.x = foo = { n: 2 };
console.log(bar.x) // ?
console.log(foo.x) // ?
```

###  18. 下面代码的输出是什么？
```js
console.log('one');
setTimeout(function() {
    console.log('two');
}, 0);
console.log('three');
```

###  19. 下面两个 alert 的结果是什么？
```js
var foo = "Hello";

(function() {
  var bar = " World";
  alert(foo + bar);
})();
```
###  20. 下面两题的结果是？解释？
```js
(function(x, f = () => x) { // 首先这里的 f = () => x 是函数声明，这里的 x 只跟形参 x 有关系
    var x; // ！！！ 注意，这里进行了函数声明，会分配新的内存地址，但是在作用域因为只进行了声明而没有赋值，所以还会找到 形参x
    var y = x; // 这里 y 的值是形参 x 的值
    x = 2; // 这里 对上面的 var x 进行赋值而形参x 的值是不受影响的（所以 f()  返回是1），此时作用域上会先找到函数内声明的 x。
    return [x, y, f()]; // ？[2, 1, 1]
})(1)

(function(x, f = () => x) {
    var y = x; // 这里只声明了y, x 还是形参x
    x = 2; // 这里改变了形参x的值，所以 f() 返回是 2
    return [x, y, f()]; // [2, 1, 2]
})(1)
```

### 24.  能否解释一下下面这段代码？
```js
Function instanceof Object; //true
Object instanceof Function; //true
```

### 26. 怎样确定 `this` 的指向？
```js
var name = "windowsName";
var a = {
    name: null,
    // name: "Cherry",
    fn: function() {
        console.log(this.name); // ?
    }
}

var f = a.fn;
f();
```
### 27.  怎么改变 this 的指向?
    
 * 使用 `apply`、`cal`l、`bind`;  
 * **加分项: 使用 ES6 的箭头函数; new 实例化一个对象;**

### 29. 解释一下JS作用域？下面代码输出是？
```js 
var scope = "global scope";
function checkscope(){
    var scope = "local scope";
    function f(){
        return scope;
    }
    return f();
}
checkscope(); // ?


var scope = "global scope";
function checkscope(){
    var scope = "local scope";
    function f(){
        return scope;
    }
    return f;
}
checkscope()(); // ?
```

**Comment by MaelWeb** [comment]
## CSS部分

### 1. CSS有哪些常用的选择器, CSS选择器的优先级是怎么样定义的， 看下列代码，<p>标签内的文字是什么颜色的？

```html
<style>
  .classA{ color:blue;}

  .classB{ color:red;}
</style>

<body>
    <p class='classB classA'> 123 </p>
</body>
```

 ### 2. margin 和 padding 有什么不一样吗？padding 可以使用负值吗？

### 3. 浮动元素 —— 怎么使用它们、它们有什么问题


### 4. position的值relative和absolute定位原点是哪里？


###  5. 如何让一个未知宽度和未知高度的元素垂直居中？


### 6. 请解释一下为什么需要清除浮动？清除浮动的方式


### 7. 有没有用过FlexBox，它有哪些特点？


###  8. 浏览器回流Reflow和重绘repaint有什么区别？


###  9. 超链接访问过后hover样式就不出现的问题是什么？如何解决？

    > 解决办法：改变CSS属性的排列顺序: L-V-H-A（link,visited,hover,active）


### 10. CSS中可以通过哪些属性定义，使得一个DOM元素不显示在浏览器可视范围内？

    > 最基本的：设置display属性为none，或者设置visibility属性为hidden
    > 技巧性：设置宽高为0，设置透明度为0，设置z-index位置在-1000


### 11. 行内元素和块级元素的具体区别是什么？行内元素的padding和margin可设置吗？

* 块级元素(block)特性：
  总是独占一行，表现为另起一行开始，而且其后的元素也必须另起一行显示;
  宽度(width)、高度(height)、内边距(padding)和外边距(margin)都可控制;

* 内联元素(inline)特性：
  和相邻的内联元素在同一行;
  宽度(width)、高度(height)、内边距的top/bottom(padding-top/padding-bottom)和外边距的top/bottom(margin-top/margin-bottom)都不可改变（也就是padding和margin的left和right是可以设置的），就是里面文字或图片的大小。


那么问题来了，浏览器还有默认的天生inline-block元素（拥有内在尺寸，可设置高宽，但不会自动换行），有哪些？
```html
  <input> 、<img> 、<button> 、<texterea> 、<label>
```

### 12. px, em, rem 的区别。


### 13. 什么是外边距重叠？重叠的结果是什么？

在CSS当中，相邻的两个盒子（可能是兄弟关系也可能是祖先关系）的外边距可以结合成一个单独的外边距。
这种合并外边距的方式被称为折叠，并且因而所结合成的外边距称为折叠外边距。

折叠结果遵循下列计算规则：
  两个相邻的外边距都是正数时，折叠结果是它们两者之间较大的值。
  两个相邻的外边距都是负数时，折叠结果是两者绝对值的较大值。
  两个外边距一正一负时，折叠结果是两者的相加的和。

###  14. rgba()和opacity的透明效果有什么不同？


###  15. Sass、LESS是什么？大家为什么要使用他们？


###  16. display:none与visibility:hidden的区别是什么？


### 17. 请用Css写一个简单的幻灯片效果页面?


###  18. 纯 CSS 实现单行居中显示文字，多行居左显示，最多两行超过用省略号结尾

```html
    <h2><p><em>单行居中，多行居左<em></p></h2>
```

```css

h2 em {
    position: relative;
    font-style: normal;
    text-align: left;
    overflow : hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
}


p {
	display: inline-block;
}

h2{
	width:320px;
	text-align: center;
	padding:10px 0;
}

```

###  19. 多列等高布局, 有哪些方法。


### 20. css 属性值中使用 `px`、数值、百分比都有什么区别？如下代码？

```css
.line-height {
     line-height: 20px;
     line-height: 1.5;
     line-height:  100%;
}

.magin {
     margin-top: 20px;
     margin-top: 20%;
}
```

### 21. 盒模型 —— 外边距、内边距和边框之间的关系?

下述代码，children实际宽度是多少px?
```html
<div class="father">
     <div class="children"></div>
</div>
```

```css
.father {
      margin: 10px;
      padding: 10px;
      border: 1px solid #000;
     width: 100px;
}

.children {
       width: 100%;
}
```

### 22. 解释一下你什么情况下会用使用 `translate()` 替代  `absolute ` 定位？使用 `translate()` 比 `absolute` 有什么优势？

### 23. 了解BFC吗？它是怎样工作的？

### 24. 设置  {box-sizing: border-box;}  对元素有什么影响？

### 25. 如何去除图片之间的间隙？这个间隙是怎么来的（比较难，可不问）？
